version: '3.9'

services:
  stackit-website-v3:
    container_name: stackit-website-v3
    restart: always
    ports:
      - 3000:3000
    # environment:
    #   - MONGO_URI=${MONGO_URI}
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
