version: '3.9'

services:
  stackit-website-v3:
    build:
      context: .
      dockerfile: ./Dockerfile

    ports:
      - 3000:3000

    volumes:
      #- /projects/stackit-website-v3:/usr/src/app
      - .:/app
      - /app/node_modules
